baseURL = "https://euraxluo.github.io"
title = "Euraxluo Blog"
theme = ["hugo-theme-bootstrap"]
copyright = "Copyright © 2016-{year} Euraxluo. All Rights Reserved."


# Pagination
paginate = 5

enableRobotsTXT = true

enableEmoji = true

[blackfriday]
  hrefTargetBlank = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
  archives = "archives"
  category = "categories"
  series = "series"
  tag = "tags"
