[[main]]
  name = "Repos"
  identifier = "repos"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "Euraxluo"
  url = "https://github.com/Euraxluo"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "cache"
  url = "https://github.com/BreezeTeam/cache"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "scheduler"
  url = "https://github.com/BreezeTeam/scheduler"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "web"
  url = "https://github.com/BreezeTeam/web"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "lang"
  url = "https://github.com/BreezeTeam/lang"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "distance_matrix"
  url = "https://github.com/BreezeTeam/distance_matrix"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "IMOMD-RRTStar-rs"
  url = "https://github.com/Euraxluo/IMOMD-RRTStar-rs"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "simplegrad"
  url = "https://github.com/Euraxluo/simplegrad"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "verb"
  url = "https://github.com/Euraxluo/verb"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  parent = "repos"
  name = "LKH-rs"
  url = "https://github.com/Euraxluo/LKH-rs"
  pre = '<i class="fab fa-fw fa-github"></i>'