email = "Euraxluo@outlook.com"
#facebook = "facebookusername"
github = "Euraxluo"
#gitlab = "gitlabusername"
#linkedin = "linkedinusername"
#stackoverflow = "stackoverflowuserid"
#twitter = "twitterusername"
#weibo = "weibousername"
zhihu = "euraxluo"
#instagram = "instagramusername"
#quora = "quorausername"
#tumblr = "tumblrusername"
#reddit = "redditusername"
#telegram = "telegramusername"
qq = "1793939176"
#dockerhub = "dockerhubusername"
#bitbucket = "bitbucketworkspaceid"
