permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 8
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "Euraxluo"  #blog name
email: "1793939176@qq.com" #email
description: "<p3>programmer<p3>" #简介
github_username:  "Euraxluo" #github
sidebar-avatar: "wxtouxiang.png" #头像
staticimg: "https://Euraxluo.github.io/static/img" #网站静态资源

# swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm" #搜索库
# disqus_shortname: "rainyalley" #disqus评论


# Gitalk评论
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 59950782f3ee3975fd60 #8e3b5021c3d411b967ae                          #生成的clientID
  clientSecret: 6ce5ca9db1c653f29754ed33c3d75b3cdf3f0ae1 #6b7fa1af068e0c0527d6c98f1fe5b61f2f71a0fc    #生成的clientSecret
  repo: Euraxluo.github.io    #仓库名称
  owner: Euraxluo    #github用户名
  admin: Euraxluo
  distractionFreeMode: true #是否启用类似FB的阴影遮罩



url: "https://Euraxluo.github.io" #博客地址
imgrepo: "https://Euraxluo.github.io/image" #博客图床

